[extend]
# useDefault will extend the default gitleaks config built in to the binary
# the latest version is located at:
# https://github.com/gitleaks/gitleaks/blob/master/config/gitleaks.toml
useDefault = true

[allowlist]
description = "global allow lists"
paths = [
  "^\\.devenv/nix-eval-cache\\.db-wal$",
  "^\\.env\\.local$",
  "^vendor/.*",
  "^node_modules/.*",
  ".*/vendor/.*",
  ".*/node_modules/.*",
  "^.php-cs-fixer.cache$"
]