# .mdformat.toml
#
wrap = "keep"       # possible values: {"keep", "no", INTEGER}
number = true       # possible values: {false, true}
end_of_line = "lf"  # possible values: {"lf", "crlf", "keep"}
validate = true     # options: {false, true}

extensions = [      # options: a list of enabled extensions (default: all installed are enabled)
  # "admon",
  # "footnote",
  "frontmatter",
  "gfm",
  # "gfm-alerts",
  # "mkdocs",
  # "myst",
  # "simple-breaks",
  "tables",
  # "toc",
  "wikilink",
]

# codeformatters = [  # options: a list of enabled code formatter languages (default: all installed are enabled)
#     "bash",
#     "json",
#     "nix",
#     "python",
# ]

# options: a list of file path pattern strings
exclude = [
  "venv/**",
  "**/vendor/**",
  "**/node_modules/**",
  "**/.terraform/**",
]
